// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH2csrot2juvWO9_4Z_MicTBBmF9AWLPo',
    appId: '1:158008347436:web:c31eba3e8e10056c963a89',
    messagingSenderId: '158008347436',
    projectId: 'uautnews-28ae4',
    authDomain: 'uautnews-28ae4.firebaseapp.com',
    storageBucket: 'uautnews-28ae4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMSJWQQQULCh-Nko4nnBpPTcDrWHXR1b8',
    appId: '1:158008347436:android:81863c65f3fa70fa963a89',
    messagingSenderId: '158008347436',
    projectId: 'uautnews-28ae4',
    storageBucket: 'uautnews-28ae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQN37_T4iIjsNsln1VSKDF0JpLlgb2Ink',
    appId: '1:158008347436:ios:aeeaab14d4cdb643963a89',
    messagingSenderId: '158008347436',
    projectId: 'uautnews-28ae4',
    storageBucket: 'uautnews-28ae4.appspot.com',
    iosClientId: '158008347436-cese40oi2kdavev3bcv216i9eape6i1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.uautNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQN37_T4iIjsNsln1VSKDF0JpLlgb2Ink',
    appId: '1:158008347436:ios:aeeaab14d4cdb643963a89',
    messagingSenderId: '158008347436',
    projectId: 'uautnews-28ae4',
    storageBucket: 'uautnews-28ae4.appspot.com',
    iosClientId: '158008347436-cese40oi2kdavev3bcv216i9eape6i1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.uautNews',
  );
}
